Item feedback form
boston-library/commonwealth-vlr-engine pull request #128
Opened 2024-02-01 17:25 UTC by jwillbpl

#100

2024-02-02 14:37 UTC, ebenenglish requested changes
Looks good, just a couple small tweaks, thanks!

2024-02-02 14:37 UTC, ebenenglish commented on config/routes.rb
> +  # get 'feedback/complete', to: 'feedback#complete'
remove this unused line

2024-02-02 14:37 UTC, ebenenglish commented on app/controllers/feedback_controller.rb
> +          redirect_to solr_document_path(params[:ark_id])
Change this to:
```ruby
redirect_to solr_document_path(@document)
```

2024-02-02 14:37 UTC, ebenenglish commented on spec/features/catalog/item_feedback_form_spec.rb
> +  it 'opens up the modal when I click the button' do
Change this to:
```ruby
it 'renders the modal popup when the button is clicked' do
```

2024-02-05 16:10 UTC, jwillbpl commented
Thank you, I pushed the changes!

2024-02-05 19:26 UTC, ebenenglish approved these changes

2024-02-05 19:30 UTC, merged